apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lab28-platform
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/tert62/Track2-Day28-2A202601650-NguyenHoangThaoTien.git
    targetRevision: refs/tags/v3.0.1
    path: deploy/kubernetes/base
  destination:
    server: https://kubernetes.default.svc
    namespace: lab28
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  revisionHistoryLimit: 5
